### ISSUE TITLE
Readme examples broken

### ISSUE THREAD

**Issue by asottile** [Yelp/named_decorator#12]
```python
>>> from named_decorator import wraps
>>> 
>>> def with_log_and_call(log_message):
...     def outer_wrapper(method):
...         @wraps(method, with_log_and_call)
...         def wrapper(*args, **kwargs):
...             print(log_message)
...             return method(*args, **kargs)
...     return wrapper
... 
>>> 
>>> @with_log_and_call('Message!')
... def f(a, b, c):
...     print(a, b, c)
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in with_log_and_call
NameError: global name 'wrapper' is not defined
```

**Comment by asottile** [comment]
via #13
